
version: '3.9'
services:
  n1:
    container_name: n1
    image: nats:2.8.4-alpine3.15
    command: "--config /config/jetstream.config"
    ports:
      - 4223:4223
      - 8223:8223
    volumes:
      - ./config:/config
      - ./persistent-data/server-n1/:/data/jetstream